name: rtd_pyflct
channels:
  - conda-forge
dependencies:
  - fftw
  - gcc_linux-64
  - graphviz!=2.42.*,!=2.43.*
  - pip
  - python=3.11
  - pip:
    - matplotlib
    - sphinx
    - sphinx-automodapi
    - sphinx-changelog
    - sphinx-gallery
    - sunpy-sphinx-theme
