version: 2.1

no-backports: &no-backports
  name: Skip any branches called cherry-pick
  command: |
    if [[ "${CIRCLE_BRANCH}" == *"cherry-pick"* || "${CIRCLE_BRANCH}" == *"backport"* ]]; then
      circleci step halt
    fi

skip-check: &skip-check
  name: Check for [ci skip]
  command: bash .circleci/early_exit.sh

merge-check: &merge-check
  name: Check if we need to merge upstream master
  command: |
    if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
      git fetch origin --tags
      git fetch origin +refs/pull/$CIRCLE_PR_NUMBER/merge:pr/$CIRCLE_PR_NUMBER/merge
      git checkout -qf pr/$CIRCLE_PR_NUMBER/merge
    fi

apt-install: &apt-install
  name: Install apt packages
  command: |
    apt update
    apt install -y graphviz build-essential libfftw3-dev

jobs:
  twine-check:
    docker:
      - image: continuumio/miniconda3
    steps:
      - run: *no-backports
      - checkout
      - run: *skip-check
      - run: *merge-check
      - run: pip install -U pep517
      - run: python -m pep517.build --source .
      - run: python -m pip install -U --user --force-reinstall twine
      - run: python -m twine check dist/*

workflows:
  version: 2

  twine-check:
    jobs:
      - twine-check

notify:
  webhooks:
    - url: https://giles.cadair.dev/circleci
